openapi: 3.0.0
info:
  title: GitHub Full Access API
  description: API для полного доступа к GitHub аккаунту, включая приватные репозитории и создание файлов.
  version: 1.0.0
servers:
  - url: https://api.github.com
    description: GitHub API
paths:
  /user/repos:
    get:
      operationId: listUserRepos
      summary: Список репозиториев пользователя
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Список репозиториев
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/Repository'
    post:
      operationId: createUserRepo
      summary: Создание репозитория пользователя
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RepositoryCreate'
      responses:
        '201':
          description: Репозиторий создан
  /repos/{owner}/{repo}:
    delete:
      operationId: deleteRepository
      summary: Удаление репозитория
      security:
        - BearerAuth: []
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
        - name: repo
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Репозиторий удален
  /repos/{owner}/{repo}/git/refs:
    get:
      operationId: listRepoBranches
      summary: Список веток репозитория
      security:
        - BearerAuth: []
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
        - name: repo
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Список веток
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Branch'
  /repos/{owner}/{repo}/issues:
    get:
      operationId: listRepoIssues
      summary: Список issues репозитория
      security:
        - BearerAuth: []
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
        - name: repo
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Список issues
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Issue'
    post:
      operationId: createRepoIssue
      summary: Создание issue в репозитории
      security:
        - BearerAuth: []
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
        - name: repo
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IssueCreate'
      responses:
        '201':
          description: Issue создан
  /repos/{owner}/{repo}/pulls:
    get:
      operationId: listRepoPullRequests
      summary: Список pull requests репозитория
      security:
        - BearerAuth: []
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
        - name: repo
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Список pull requests
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PullRequest'
    post:
      operationId: createRepoPullRequest
      summary: Создание pull request в репозитории
      security:
        - BearerAuth: []
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
        - name: repo
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PullRequestCreate'
      responses:
        '201':
          description: Pull request создан
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Repository:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        private:
          type: boolean
    RepositoryCreate:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        private:
          type: boolean
        auto_init:
          type: boolean
          description: Whether the repository is initialized with a README
    Branch:
      type: object
      properties:
        name:
          type: string
    Issue:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        body:
          type: string
        state:
          type: string
    IssueCreate:
      type: object
      properties:
        title:
          type: string
        body:
          type: string
        assignees:
          type: array
          items:
            type: string
    PullRequest:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        body:
          type: string
        state:
          type: string
    PullRequestCreate:
      type: object
      properties:
        title:
          type: string
        head:
          type: string
        base:
          type: string
        body:
          type: string
